/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package todomvc.automation;

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.time.Duration;

class ToDoMVCTest {
    private static ChromeDriver driver;

    static void addItemToList(String item){
        WebElement newItemBox = driver.findElement(By.cssSelector(".new-todo"));
        newItemBox.sendKeys(item);
        newItemBox.sendKeys(Keys.RETURN);
    }
    static WebElement viewList(){
        return driver.findElement(By.cssSelector(".todo-list"));
    }

    @BeforeEach
    void launchBrowser() throws InterruptedException {
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.get("https://todomvc.com");
        WebElement reactLinkText = driver.findElement(By.linkText("React"));
        reactLinkText.click();
    }

    @Test
    void shouldPrintPageTitle() {
        Assertions.assertEquals("React • TodoMVC", driver.getTitle());
    }
    @Test
    void addSingleItem() {
        addItemToList("Buy some milk");
        Assertions.assertEquals("Buy some milk", viewList().getText());
    }
    @Test
    void addMultipleItems() {
        addItemToList("Buy some milk");
        addItemToList("Buy some bread");
        Assertions.assertEquals("Buy some milk\n" + "Buy some bread", viewList().getText());
    }

    @AfterEach
    void quitBrowser(){driver.quit(); }


}
